# CI RastreaDor
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rastredor

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar dependencias
        run: mvn install -DskipTests

      - name: Rodar Checkstyle
        run: mvn checkstyle:check

      - name: Rodar testes
        run: mvn test
